# Generated by Django 2.2.9 on 2020-09-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nome_materia', models.CharField(max_length=45)),
                ('descricao', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
