# Generated by Django 2.2.9 on 2020-09-26 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('numero_aulas', models.IntegerField()),
                ('Funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Funcionario')),
                ('Materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Materia')),
            ],
        ),
    ]
